(() => {
  "use strict";
  const sessao = JSON.parse(localStorage.getItem("usuarioLogado") || "null");
  const token = sessao?.token;
  if (!token) { window.location.href = "login.html"; return; }

  const $ = (id) => document.getElementById(id);
  const modalLancamento = new bootstrap.Modal($("modalLancamento"));
  const modalBaixa = new bootstrap.Modal($("modalBaixa"));
  const modalConta = new bootstrap.Modal($("modalConta"));
  const modalCategoria = new bootstrap.Modal($("modalCategoria"));
  let lancamentos = [], categorias = [], contas = [], clientes = [], tipoFiltro = "", fluxoChart = null;

  const dinheiro = (v) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
  const esc = (v) => String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
  const isoDate = (v) => { if(!v) return ""; const d=new Date(v); if(Number.isNaN(d.getTime())) return ""; return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
  const dataBr = (v) => v ? new Date(v).toLocaleDateString("pt-BR") : "Sem vencimento";
  const nomeCliente = (c) => c?.nomeFantasia || c?.razaoSocial || c?.responsavel || `Cliente #${c?.clienteid || ""}`;
  const isVencido = (l) => l.status === "ABERTO" && l.dataVencimento && new Date(l.dataVencimento) < new Date(new Date().setHours(0,0,0,0));

  async function api(path, options={}) {
    const headers = { Authorization:`Bearer ${token}`, ...(options.body!==undefined?{"Content-Type":"application/json"}:{}), ...(options.headers||{}) };
    const r = await fetch(`${API_URL}${path}`, {...options, headers});
    const d = await r.json().catch(()=>null);
    if(!r.ok){ const e=new Error(d?.error || `Erro HTTP ${r.status}`); e.status=r.status; throw e; }
    return d;
  }
  function erro(e,t="Não foi possível concluir"){ console.error(e); Swal.fire({icon:"error",title:t,text:e?.message||"Erro inesperado."}); }
  function sucesso(t){ Swal.fire({icon:"success",title:t,timer:1300,showConfirmButton:false}); }

  async function carregarDashboard(){
    const d=await api("/financeiro/dashboard");
    $("kpiSaldo").textContent=dinheiro(d.saldoDisponivel); $("kpiReceber").textContent=dinheiro(d.contasReceber); $("kpiPagar").textContent=dinheiro(d.contasPagar); $("kpiProjetado").textContent=dinheiro(d.saldoProjetado); $("kpiVencidos").textContent=dinheiro(d.vencidosValor); $("kpiVencidosQtd").textContent=`${d.vencidosQuantidade||0} lançamento${d.vencidosQuantidade===1?"":"s"} vencido${d.vencidosQuantidade===1?"":"s"}`; $("recebidoMes").textContent=dinheiro(d.recebidoMes); $("pagoMes").textContent=dinheiro(d.pagoMes); $("resultadoMes").textContent=dinheiro(d.resultadoMes); renderProximos(d.ultimos||[]);
  }
  async function carregarFluxo(){
    const dados=await api("/financeiro/fluxo?meses=6"); const ctx=$("fluxoChart"); if(fluxoChart) fluxoChart.destroy();
    fluxoChart=new Chart(ctx,{type:"bar",data:{labels:dados.map(x=>x.mes),datasets:[{label:"Entradas",data:dados.map(x=>x.entradas),backgroundColor:"rgba(25,135,84,.72)",borderRadius:6},{label:"Saídas",data:dados.map(x=>x.saidas),backgroundColor:"rgba(220,53,69,.62)",borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{usePointStyle:true,boxWidth:8,font:{size:10}}}},scales:{x:{grid:{display:false},ticks:{font:{size:10}}},y:{beginAtZero:true,ticks:{font:{size:10},callback:v=>"R$ "+Number(v).toLocaleString("pt-BR")},grid:{color:"#f0f1f3"}}}}});
  }
  async function carregarLancamentos(){
    const q=new URLSearchParams(); if(tipoFiltro)q.set("tipo",tipoFiltro); if($("filtroStatus").value)q.set("status",$("filtroStatus").value); if($("filtroVencimento").value)q.set("vencimento",$("filtroVencimento").value); if($("buscaFinanceiro").value.trim())q.set("busca",$("buscaFinanceiro").value.trim()); lancamentos=await api(`/financeiro/lancamentos${q.toString()?`?${q}`:""}`); renderLancamentos();
  }
  async function carregarAuxiliares(){
    const [cats,cts,cls]=await Promise.all([api("/financeiro/categorias"),api("/financeiro/contas"),api("/clientes")]); categorias=cats||[]; contas=cts||[]; clientes=Array.isArray(cls)?cls:(cls?.clientes||cls?.data||[]); renderConfiguracoes(); atualizarSelects();
  }
  async function atualizarTudo(){ try{ await Promise.all([carregarDashboard(),carregarFluxo(),carregarLancamentos(),carregarAuxiliares()]); }catch(e){ if(e.status===401){localStorage.removeItem("usuarioLogado");window.location.href="login.html";return;} erro(e,"Erro ao carregar financeiro"); } }

  function renderProximos(lista){ const abertos=lista.filter(x=>x.status==="ABERTO").slice(0,6); $("emptyProximos").classList.toggle("d-none",abertos.length>0); $("listaProximos").innerHTML=abertos.map(l=>`<div class="proximo-item"><div class="proximo-icon ${l.tipo.toLowerCase()}">${l.tipo==="ENTRADA"?"↗":"↘"}</div><div class="proximo-main"><strong>${esc(l.descricao)}</strong><span>${esc(l.clienteNome||l.categoria?.nome||"Sem categoria")}</span></div><div class="proximo-valor"><strong>${dinheiro(l.valor)}</strong><span class="${isVencido(l)?"vencimento-danger":""}">${isVencido(l)?"Vencido · ":""}${dataBr(l.dataVencimento)}</span></div></div>`).join(""); }
  function statusBadge(l){ if(l.status==="CANCELADO")return `<span class="fin-status cancelado">Cancelado</span>`; if(l.status==="PAGO")return `<span class="fin-status pago">${l.tipo==="ENTRADA"?"Recebido":"Pago"}</span>`; if(isVencido(l))return `<span class="fin-status vencido">Vencido</span>`; return `<span class="fin-status aberto">Em aberto</span>`; }
  function renderLancamentos(){ const body=$("listaLancamentos"); $("emptyLancamentos").classList.toggle("d-none",lancamentos.length>0); body.innerHTML=lancamentos.map(l=>`<tr><td><div class="fin-desc"><strong>${esc(l.descricao)}</strong><span>${esc(l.documento||"")}</span></div></td><td>${esc(l.clienteNome||"-")}<br><span class="origin-badge">${l.origem==="PROPOSTA"?`Proposta ${esc(l.proposta?.numero||l.documento||"")}`:"Manual"}</span></td><td>${esc(l.categoria?.nome||"-")}</td><td class="${isVencido(l)?"vencimento-danger":""}">${dataBr(l.dataVencimento)}</td><td class="fin-value ${l.tipo.toLowerCase()}">${l.tipo==="SAIDA"?"− ":"+ "}${dinheiro(l.valor)}</td><td>${statusBadge(l)}</td><td><div class="action-menu">${l.status==="ABERTO"?`<button data-baixar="${l.lancamentofinanceiroid}">Baixar</button><button data-editar="${l.lancamentofinanceiroid}">Editar</button><button data-cancelar="${l.lancamentofinanceiroid}">Cancelar</button>`:l.status==="PAGO"?`<button data-reabrir="${l.lancamentofinanceiroid}">Reabrir</button>`:""}${l.origem==="MANUAL"?`<button data-excluir="${l.lancamentofinanceiroid}">Excluir</button>`:""}</div></td></tr>`).join(""); }
  function renderConfiguracoes(){ $("listaContas").innerHTML=contas.length?contas.map(c=>`<div class="config-item"><div><strong>${esc(c.nome)}</strong><span>${esc(c.tipo)}${c.banco?` · ${esc(c.banco)}`:""}</span></div><div class="saldo">${dinheiro(c.saldoAtual)}</div></div>`).join(""):`<div class="empty-state">Cadastre a primeira conta para controlar saldos.</div>`; $("listaCategorias").innerHTML=categorias.map(c=>`<div class="config-item"><div><strong>${esc(c.nome)}</strong><span>${c.tipo==="ENTRADA"?"Receita":"Despesa"}</span></div><span>${esc(c.descricao||"")}</span></div>`).join(""); }
  function atualizarSelects(){ const clienteOpts=`<option value="">Sem cliente vinculado</option>`+clientes.sort((a,b)=>nomeCliente(a).localeCompare(nomeCliente(b),"pt-BR")).map(c=>`<option value="${c.clienteid}">${esc(nomeCliente(c))}</option>`).join(""); $("finCliente").innerHTML=clienteOpts; const contaOpts=`<option value="">Definir na baixa</option>`+contas.filter(c=>c.ativo!==false).map(c=>`<option value="${c.contafinanceiraid}">${esc(c.nome)}</option>`).join(""); $("finConta").innerHTML=contaOpts; $("baixaConta").innerHTML=contaOpts; atualizarCategoriasSelect(); }
  function atualizarCategoriasSelect(){ const tipo=$("finTipo").value; $("finCategoria").innerHTML=`<option value="">Sem categoria</option>`+categorias.filter(c=>c.ativo!==false&&c.tipo===tipo).map(c=>`<option value="${c.categoriafinanceiraid}">${esc(c.nome)}</option>`).join(""); }
  function novoLancamento(tipo){ $("formLancamento").reset(); $("lancamentoId").value=""; $("finTipo").value=tipo; $("finCompetencia").value=isoDate(new Date()); $("finParcelas").value=1; $("finIntervalo").value=30; $("tituloLancamento").textContent=tipo==="ENTRADA"?"Nova entrada":"Nova saída"; document.querySelectorAll(".parcela-only").forEach(x=>x.classList.remove("d-none")); atualizarCategoriasSelect(); modalLancamento.show(); }
  async function editarLancamento(id){ const l=await api(`/financeiro/lancamentos/${id}`); $("lancamentoId").value=l.lancamentofinanceiroid; $("finTipo").value=l.tipo; $("finDescricao").value=l.descricao||""; $("finValor").value=Number(l.valor||0); $("finCompetencia").value=isoDate(l.dataCompetencia); $("finVencimento").value=isoDate(l.dataVencimento); $("finCliente").value=l.clienteId||""; atualizarCategoriasSelect(); $("finCategoria").value=l.categoriaFinanceiraId||""; $("finConta").value=l.contaFinanceiraId||""; $("finFormaPagamento").value=l.formaPagamento||""; $("finDocumento").value=l.documento||""; $("finObservacoes").value=l.observacoes||""; document.querySelectorAll(".parcela-only").forEach(x=>x.classList.add("d-none")); $("tituloLancamento").textContent="Editar lançamento"; modalLancamento.show(); }
  function abrirBaixa(id){ const l=lancamentos.find(x=>x.lancamentofinanceiroid===Number(id)); if(!l)return; $("baixaId").value=id; $("baixaValor").value=Number(l.valor||0); $("baixaData").value=isoDate(new Date()); $("baixaConta").value=l.contaFinanceiraId||""; $("baixaForma").value=l.formaPagamento||""; modalBaixa.show(); }

  $("btnNovaEntrada").addEventListener("click",()=>novoLancamento("ENTRADA")); $("btnNovaSaida").addEventListener("click",()=>novoLancamento("SAIDA")); $("btnNovaConta").addEventListener("click",()=>{$("formConta").reset();$("contaSaldo").value=0;modalConta.show();}); $("btnNovaCategoria").addEventListener("click",()=>{$("formCategoria").reset();modalCategoria.show();}); $("finTipo").addEventListener("change",atualizarCategoriasSelect);
  $("tabsFinanceiro").addEventListener("click",e=>{const b=e.target.closest("button[data-tipo]");if(!b)return;tipoFiltro=b.dataset.tipo||"";$("tabsFinanceiro").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));carregarLancamentos().catch(erro);});
  $("btnAtualizarFinanceiro").addEventListener("click",()=>carregarLancamentos().catch(erro)); $("filtroStatus").addEventListener("change",()=>carregarLancamentos().catch(erro)); $("filtroVencimento").addEventListener("change",()=>carregarLancamentos().catch(erro)); let timer; $("buscaFinanceiro").addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(()=>carregarLancamentos().catch(erro),300);});
  $("btnSincronizarFaturadas").addEventListener("click",async()=>{try{const d=await api("/financeiro/sincronizar-faturadas",{method:"POST",body:"{}"});sucesso(`${d.quantidade||0} proposta(s) sincronizada(s)`);await atualizarTudo();}catch(e){erro(e);}});

  $("formLancamento").addEventListener("submit",async e=>{e.preventDefault();try{const id=$("lancamentoId").value; const data={tipo:$("finTipo").value,descricao:$("finDescricao").value.trim(),valor:Number($("finValor").value),dataCompetencia:$("finCompetencia").value||null,dataVencimento:$("finVencimento").value||null,clienteId:$("finCliente").value||null,categoriaFinanceiraId:$("finCategoria").value||null,contaFinanceiraId:$("finConta").value||null,formaPagamento:$("finFormaPagamento").value||null,documento:$("finDocumento").value||null,observacoes:$("finObservacoes").value||null,totalParcelas:Number($("finParcelas").value||1),intervaloDias:Number($("finIntervalo").value||30)}; await api(id?`/financeiro/lancamentos/${id}`:"/financeiro/lancamentos",{method:id?"PUT":"POST",body:JSON.stringify(data)});modalLancamento.hide();sucesso("Lançamento salvo");await atualizarTudo();}catch(e2){erro(e2);}});
  $("formBaixa").addEventListener("submit",async e=>{e.preventDefault();try{await api(`/financeiro/lancamentos/${$("baixaId").value}/baixar`,{method:"POST",body:JSON.stringify({valorPago:Number($("baixaValor").value),dataPagamento:$("baixaData").value,contaFinanceiraId:$("baixaConta").value||null,formaPagamento:$("baixaForma").value||null})});modalBaixa.hide();sucesso("Baixa realizada");await atualizarTudo();}catch(er){erro(er);}});
  $("formConta").addEventListener("submit",async e=>{e.preventDefault();try{await api("/financeiro/contas",{method:"POST",body:JSON.stringify({nome:$("contaNome").value.trim(),tipo:$("contaTipo").value,saldoInicial:Number($("contaSaldo").value||0),banco:$("contaBanco").value||null,agencia:$("contaAgencia").value||null,conta:$("contaNumero").value||null})});modalConta.hide();sucesso("Conta criada");await carregarAuxiliares();await carregarDashboard();}catch(er){erro(er);}});
  $("formCategoria").addEventListener("submit",async e=>{e.preventDefault();try{await api("/financeiro/categorias",{method:"POST",body:JSON.stringify({nome:$("catNome").value.trim(),tipo:$("catTipo").value,descricao:$("catDescricao").value||null})});modalCategoria.hide();sucesso("Categoria criada");await carregarAuxiliares();}catch(er){erro(er);}});
  $("listaLancamentos").addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;try{if(b.dataset.baixar) abrirBaixa(b.dataset.baixar); if(b.dataset.editar) await editarLancamento(b.dataset.editar); if(b.dataset.reabrir){await api(`/financeiro/lancamentos/${b.dataset.reabrir}/reabrir`,{method:"POST",body:"{}"});await atualizarTudo();} if(b.dataset.cancelar){const c=await Swal.fire({icon:"warning",title:"Cancelar lançamento?",showCancelButton:true,confirmButtonText:"Cancelar lançamento",cancelButtonText:"Voltar"});if(c.isConfirmed){await api(`/financeiro/lancamentos/${b.dataset.cancelar}/cancelar`,{method:"POST",body:"{}"});await atualizarTudo();}} if(b.dataset.excluir){const c=await Swal.fire({icon:"warning",title:"Excluir lançamento?",text:"Esta ação não poderá ser desfeita.",showCancelButton:true,confirmButtonText:"Excluir",cancelButtonText:"Voltar"});if(c.isConfirmed){await api(`/financeiro/lancamentos/${b.dataset.excluir}`,{method:"DELETE"});await atualizarTudo();}}}catch(er){erro(er);}});

  atualizarTudo();
})();
