(()=>{
const $=id=>document.getElementById(id),token=JSON.parse(localStorage.getItem("usuarioLogado")||"null")?.token;
const keys="codigo nome classificacao tipo codigoBarras codigoFabricante fabricante fornecedor unidade unidadeCompra grupo secao centroCusto ncm cest nbs regraFiscal origem custo estoqueFisico estoqueFiscal preFaturado disponivel especificacao observacoes".split(" ");let fotos=[];
async function api(path,method="GET",body){const res=await fetch(API_URL+path,{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw Error(data.error||"Erro ao salvar");return data;}
function preview(){ $("previewFotos").replaceChildren();fotos.forEach((src,index)=>{const img=document.createElement("img");img.src=src;img.style.cssText="width:100px;height:100px;object-fit:contain;margin:8px";img.alt="Foto do material";const btn=document.createElement("button");btn.type="button";btn.textContent="Remover foto";btn.onclick=()=>{fotos.splice(index,1);preview();};$("previewFotos").append(img,btn);});}
function novo(){ $("formMaterial").reset();$("materialId").value="";fotos=[];preview();}
async function listar(){const data=await api("/servicos");$("listaMateriais").replaceChildren();for(const s of data.filter(s=>s.dadosMaterial)){const card=document.createElement("div");card.className="sba-card";const name=document.createElement("strong");name.textContent=`${s.codigo||""} — ${s.nome}`;const btn=document.createElement("button");btn.textContent="Editar";btn.onclick=()=>{novo();$("materialId").value=s.servicoid;const d={...s.dadosMaterial,...s};keys.forEach(k=>$(k).value=d[k]??"");$("ativo").checked=s.ativo;for(const k of ["vista","28","35","padrao"]){$("margem"+k).value=s.dadosMaterial.precos?.[k]?.margem??"";$("preco"+k).value=s.dadosMaterial.precos?.[k]?.valor??"";}fotos=s.dadosMaterial.fotos||[];preview();$("formMaterial").scrollIntoView();};card.append(name,btn);$("listaMateriais").append(card);}}
for(const k of ["vista","28","35","padrao"])$("margem"+k).oninput=()=>{const margem=Number($("margem"+k).value)/100;if(margem>=0&&margem<1)$("preco"+k).value=(Number($("custo").value)/(1-margem)).toFixed(2);};
$("fotos").onchange=async()=>{try{for(const file of $("fotos").files){if(fotos.length>=10)throw Error("Limite de 10 fotos");if(file.size>10*1024*1024)throw Error("Foto maior que 10 MB");const image=await createImageBitmap(file);const factor=Math.min(1,500/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=image.width*factor;canvas.height=image.height*factor;canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);fotos.push(canvas.toDataURL("image/jpeg",0.8));image.close();}preview();}catch(e){$("mensagem").textContent=e.message;}};
$("novo").onclick=novo;$("formMaterial").onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(keys.map(k=>[k,$(k).type==="number"?Number($(k).value):$(k).value]));d.fotos=fotos;d.precos=Object.fromEntries(["vista","28","35","padrao"].map(k=>[k,{margem:Number($("margem"+k).value),valor:Number($("preco"+k).value)}]));const body={codigo:d.codigo||null,nome:d.nome,unidade:d.unidade,custo:d.custo,descricao:d.especificacao,observacoes:d.observacoes,ativo:$("ativo").checked,dadosMaterial:d};const id=$("materialId").value;const s=await api("/servicos"+(id?"/"+id:""),id?"PUT":"POST",body);$("materialId").value=s.servicoid;$("mensagem").textContent="Material salvo.";await listar();}catch(e){$("mensagem").textContent=e.message;}};
window.addEventListener("configuracao-sistema",async({detail:c})=>{if(!c.composicaoCustos){location.replace("perfil.html");return;}try{await listar();}catch(e){$("mensagem").textContent=e.message;}});
})();
