(()=>{
const $=id=>document.getElementById(id),token=JSON.parse(localStorage.getItem("usuarioLogado")||"null")?.token;
let config,clientes=[],catalogo=[];
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
async function api(path,method="GET",body){const res=await fetch(API_URL+path,{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await res.json();if(!res.ok)throw Error(d.error||d.message||"Falha ao salvar");return d;}
function input(value,type="text"){const el=document.createElement("input");el.type=type;el.value=value??"";if(type==="number"){el.min=0;el.step="any";}el.oninput=calcular;return el;}
function row(tipo,m={}){const el=document.createElement("div");el.className="sba-row "+tipo;const keys=tipo==="materiais"?["descricao","especificacao","quantidade","custoUnitario"]:["descricao","dias","pessoas","horasDia","valorHora"];keys.forEach((k,i)=>{const defaults={quantidade:1,dias:1,pessoas:1,horasDia:8,valorHora:37.5,custoUnitario:0};const field=input(m[k]??defaults[k],i<(tipo==="materiais"?2:1)?"text":"number");field.dataset.key=k;const label={descricao:"Descrição",especificacao:"Especificação",quantidade:"Quantidade",custoUnitario:"Custo unitário",dias:"Dias",pessoas:"Pessoas",horasDia:"Horas por dia",valorHora:"Valor por hora"}[k];field.placeholder=label;field.setAttribute("aria-label",label);const wrap=document.createElement("label");const caption=document.createElement("span");caption.textContent=label;wrap.append(caption,field);el.append(wrap);});if(tipo==="materiais"&&catalogo.length){const select=document.createElement("select");select.add(new Option("Do catálogo",""));catalogo.forEach(s=>select.add(new Option(s.nome,s.servicoid)));select.onchange=()=>{const s=catalogo.find(s=>s.servicoid===Number(select.value));if(!s)return;el.querySelector('[data-key="descricao"]').value=s.nome;el.querySelector('[data-key="especificacao"]').value=s.dadosMaterial?.especificacao||s.descricao||"";el.querySelector('[data-key="custoUnitario"]').value=s.custo||0;calcular();};const wrap=document.createElement("label");const caption=document.createElement("span");caption.textContent="Catálogo";wrap.append(caption,select);el.prepend(wrap);}const remove=document.createElement("button");remove.type="button";remove.textContent="Remover";remove.onclick=()=>{el.remove();calcular();};el.append(remove);$(tipo).append(el);calcular();}
function comp(){const read=id=>[...$(id).children].map(el=>Object.fromEntries([...el.querySelectorAll("[data-key]")].map(f=>[f.dataset.key,f.type==="number"?Number(f.value):f.value])));return{materiais:read("materiais"),maoObra:read("maoObra"),margem:Number($("margem").value)/100,imposto:Number($("imposto").value)/100};}
function calcular(){const c=comp(),mat=c.materiais.reduce((s,m)=>s+m.quantidade*m.custoUnitario,0),labor=c.maoObra.reduce((s,m)=>s+m.dias*m.pessoas*m.horasDia*m.valorHora,0),cost=mat+labor,price=cost/(1-c.margem),tax=price*c.imposto;$("totais").replaceChildren();for(const [label,value,classe] of [["Materiais",mat,""],["Mão de obra",labor,""],["Custo total",cost,""],["Preço de venda",price,"price-total"],["Imposto estimado",tax,""],["Receita após imposto",price-tax,""],["Lucro após custo e imposto",price-tax-cost,"profit-total"]]){const card=document.createElement("div");card.className="budget-total "+classe;const caption=document.createElement("span");caption.textContent=label;const total=document.createElement("strong");total.textContent=money(value);card.append(caption,total);$("totais").append(card);};}
function contatos(p={}){const c=clientes.find(c=>c.clienteid===Number($("cliente").value));for(const [id,values,chosen] of [["contato",c?[c.responsavel,...[1,2,3,4].flatMap(i=>[c["nomeEmail"+i],c["nomeTelefone"+i]])]:[],p.contatoDestinatario],["email",c?[1,2,3,4].map(i=>c["email"+i]):[],p.emailDestinatario]]){const el=$(id);el.replaceChildren(new Option("Selecione",""));for(const v of new Set(values.filter(Boolean)))el.add(new Option(v,v));el.value=chosen||"";}}
function novo(){ $("formOrcamento").reset();$("orcamentoId").value="";$("materiais").replaceChildren();$("maoObra").replaceChildren();$("escopo").value=config.textoEscopo;contatos();calcular();}
async function listar(){const propostas=await api("/propostas");$("listaOrcamentos").replaceChildren();for(const p of propostas.filter(p=>p.composicaoCustos)){const card=document.createElement("div");card.className="sba-card";const title=document.createElement("strong");title.textContent=`${p.numero} — ${p.titulo} — ${money(p.subtotal)}`;const editar=document.createElement("button");editar.textContent="Editar";editar.onclick=async()=>{try{const d=await api("/propostas/"+p.propostaid);novo();$("orcamentoId").value=d.propostaid;$("cliente").value=d.clienteId;contatos(d);for(const [id,k] of [["titulo","titulo"],["descricao","descricao"],["escopo","escopo"],["pagamento","condicoesPagamento"],["prazo","prazoEntrega"]])$(id).value=d[k]||"";$("validade").value=d.dataValidade?.slice(0,10)||"";$("margem").value=d.composicaoCustos.margem*100;$("imposto").value=d.composicaoCustos.imposto*100;d.composicaoCustos.materiais.forEach(m=>row("materiais",m));d.composicaoCustos.maoObra.forEach(m=>row("maoObra",m));calcular();$("formOrcamento").scrollIntoView();}catch(e){$("mensagem").textContent=e.message;}};const pdf=document.createElement("button");pdf.textContent="Gerar PDF";pdf.onclick=async()=>{try{await api(`/propostas/${p.propostaid}/pdf`,"POST",{});location.href=`${API_URL}/propostas/${p.propostaid}/download?token=${encodeURIComponent(token)}`;}catch(e){$("mensagem").textContent=e.message;}};card.append(title,editar,pdf);$("listaOrcamentos").append(card);}}
$("cliente").onchange=()=>contatos();$("adicionarMaterial").onclick=()=>row("materiais");$("adicionarMaoObra").onclick=()=>row("maoObra");$("novo").onclick=novo;$("margem").oninput=calcular;$("imposto").oninput=calcular;
$("formOrcamento").onsubmit=async e=>{e.preventDefault();try{const body={clienteId:Number($("cliente").value),titulo:$("titulo").value,descricao:$("descricao").value,escopo:$("escopo").value,contatoDestinatario:$("contato").value,emailDestinatario:$("email").value,composicaoCustos:comp(),dataValidade:$("validade").value||null,prazoEntrega:$("prazo").value,condicoesPagamento:$("pagamento").value,tipoProposta:"SERVICOS"};const id=$("orcamentoId").value;const p=await api("/propostas"+(id?"/"+id:""),id?"PUT":"POST",body);$("orcamentoId").value=p.propostaid;$("mensagem").textContent="Orçamento salvo.";await listar();}catch(e){$("mensagem").textContent=e.message;}};
window.addEventListener("configuracao-sistema",async({detail:c})=>{config=c;if(!c.composicaoCustos){location.replace("perfil.html");return;}try{[clientes,catalogo]=await Promise.all([api("/clientes"),api("/servicos")]);catalogo=catalogo.filter(s=>s.ativo&&s.dadosMaterial);$("cliente").replaceChildren(new Option("Selecione",""));clientes.forEach(c=>$("cliente").add(new Option(c.razaoSocial||c.nomeFantasia,c.clienteid)));novo();await listar();}catch(e){$("mensagem").textContent=e.message;}});
})();
